### ISSUE TITLE
Pressing ESC on character menu always goes to the main menu even when submenus (like the artifact menu) are open

### ISSUE THREAD

**Issue by ragmats** [Hibiscus14/ESCapism#1]
In cases where sub menus are open on the character menu, such as the artifact menu, I would expect the ESC key to simply close the artifact menu and stay on the character menu. Currently, pressing ESC on the character menu with the artifact menu open leaves the character menu entirely back to the main menu.

**Comment by Hibiscus14** [comment]
Thanks for your feedback! This issue has now been fixed in the current update.
